version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      NODE_ENV: docker
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
     - MONGODB_ROOT_PASSWORD=a1b2c3
    command: mongod --smallfiles --bind_ip_all
  handler:
      container_name: handler
      restart: always
      build:
       context: .
       args:
         IS_HANDLER: 1
      links:
        - mongodb
      depends_on:
        - mongodb
